### ISSUE TITLE
Cannot read property while deleting a item

### ISSUE THREAD

**Issue by adriaandotcom** [phobosjs/phobos.js#26]
When running `DELETE` on `http://localhost:5020/tasks/56b9e60ff6b55a2c279f488a`:

```
TypeError: Cannot read property &#39;remove&#39; of null
<br> &nbsp; &nbsp;at mutate (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/phobosjs/middleware/mutate.js:35:25)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at next (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/route.js:131:13)
<br> &nbsp; &nbsp;at applyScope (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/phobosjs/middleware/apply-scope.js:30:29)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at next (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/route.js:131:13)
<br> &nbsp; &nbsp;at ownership (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/phobosjs/middleware/ownership.js:19:29)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at next (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/route.js:131:13)
<br> &nbsp; &nbsp;at scopeCatch (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/phobosjs/middleware/scope-catch.js:40:14)
<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/layer.js:95:5)
<br> &nbsp; &nbsp;at next (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/express/lib/router/route.js:131:13)
<br> &nbsp; &nbsp;at /Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/phobosjs/middleware/query-runner.js:60:28
<br> &nbsp; &nbsp;at Query.&lt;anonymous&gt; (/Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/mongoose/lib/query.js:2149:28)
<br> &nbsp; &nbsp;at /Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/kareem/index.js:177:19
<br> &nbsp; &nbsp;at /Users/Adriaan/MGMco/phobosjs-sampleapp/node_modules/kareem/index.js:109:16
```

**Comment by mtimofiiv** [comment]
<img src="https://cloud.githubusercontent.com/assets/428948/12918075/5365d744-cf3d-11e5-8f07-523400a0a11f.gif" width="100%">

Appears that [this](https://github.com/phobosjs/phobos.js/blob/master/middleware/mutate.js#L35) is not functioning correctly on deletes.

**Comment by mtimofiiv** [comment]
This was fixed a few releases ago.
